// flow-typed signature: 389073efd68450bd1bd5dc3ad3c1cac7
// flow-typed version: <<STUB>>/lodash.get_v4.4.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.get'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.get' {
  declare module.exports: any;
}
