// flow-typed signature: 8a1ddcde57b455a6ff5df58d15991d01
// flow-typed version: <<STUB>>/lodash.pickby_v4.6.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.pickby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.pickby' {
  declare module.exports: any;
}
