version: 2.1

orbs:
  javascript: wealthsimple/javascript@dev:SethDavenport-patch-1
  sonarqube: wealthsimple/sonarqube@dev:master

references:
  javascript_params: &javascript_params
    node_version: '12'

jobs:
  test:
    executor: javascript/node
    steps:
      - checkout
      - javascript/attach_code_workspace
      - javascript/yarn_install_dependencies
      - javascript/run_unit_tests
      - sonarqube/scan
  convert_to_typescript:
    executor: javascript/node
    steps:
      - checkout
      - javascript/attach_code_workspace
      - run:
          command: ./scripts/tsconvert.bash

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - javascript/security:
          name: security
          context: wealthsimple
      - test:
          context: wealthsimple
          name: test
      - javascript/static_checks:
          context: wealthsimple
          name: static_checks
      - convert_to_typescript:
          context: wealthsimple
      - javascript/semantic_release:
          context: wealthsimple
          npm_publish_publicly: true
          requires:
            - static_checks
            - security
            - test
            - convert_to_typescript
          filters:
            branches:
              only: master
