version: 2.1

orbs:
  javascript: wealthsimple/javascript@dev:master
  sonarqube: wealthsimple/sonarqube@dev:master

references:
  javascript_params: &javascript_params
    node_version: '12'

jobs:
  test:
    executor: javascript/node
    steps:
      - checkout
      - javascript/attach_code_workspace
      - javascript/yarn_install_dependencies
      - javascript/run_unit_tests
      - sonarqube/scan

  check_typescript_convertability:
    executor: javascript/node
    steps:
      - checkout
      - javascript/attach_code_workspace
      - run:
          name: Convert to TypeScript
          command: ./scripts/tsconvert.bash

  update_typescript_release_branch:
    executor: javascript/node
    steps:
      - checkout
      - javascript/attach_code_workspace
      - run:
          name: Update release branch if necessary
          command: |
            git checkout typescript-releases
            git merge master
            git config user.email "noreply@wealthsimple.com"
            git config user.name "Wolfbot"
            git push origin typescript-releases

  publish_typescript:
    executor: javascript/node
    steps:
      - checkout
      - javascript/attach_code_workspace
      - run:
          name: Convert to TypeScript
          command: ./scripts/tsconvert.bash
      - run:
          name: Release
          command: |
            # The tsconvert script reconfigures package.json to use the -ts package
            # name and the typescript-releases branch, to keep the TS releases separate
            # from the flow ones on master.
            #
            # This package is on npm, not Nexus.
            export NPM_TOKEN="${PUBLIC_NPM_TOKEN}"
            npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
            GITHUB_TOKEN="${DEVTOOLS_GITHUB_API_TOKEN}" yarn run semantic-release

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - javascript/security:
          name: security
          context: wealthsimple
          filters:
            branches:
              ignore:
                - typescript-releases

      - test:
          context: wealthsimple
          name: test
          filters:
            branches:
              ignore:
                - typescript-releases

      - javascript/static_checks:
          context: wealthsimple
          name: static_checks
          filters:
            branches:
              ignore:
                - typescript-releases

      - javascript/semantic_release:
          name: Semantic Release (FlowType)
          context: wealthsimple
          npm_publish_publicly: true
          requires:
            - static_checks
            - security
            - test
            - check_typescript_convertability
          filters:
            branches:
              only: master

      - check_typescript_convertability:
          context: wealthsimple
          filters:
            branches:
              ignore:
                - typescript-releases

      - update_typescript_release_branch:
          name: Semantic Release (TypeScript)
          context: wealthsimple
          requires:
            - static_checks
            - security
            - test
            - check_typescript_convertability
          filters:
            branches:
              only: master
       
      - publish_typescript:
          name: Semantic Release (TypeScript)
          context: Wealthsimple
          filters:
            branches:
              only: typescript-releases
