version: 2.1

orbs:
  micro-app: wealthsimple/micro-app@dev:master

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - micro-app/checkout:
          name: checkout
      - micro-app/security:
          name: security
          context: wealthsimple
          requires:
            - checkout
      - micro-app/test:
          name: test
          requires:
            - checkout
      - micro-app/coverage:
          name: coverage
          requires:
            - checkout
      - micro-app/static_checks:
          name: static_checks
          requires:
            - checkout
      - micro-app/semantic_release:
          name: semantic_release
          context: wealthsimple
          filters:
            branches:
              only: master
          requires:
            - checkout
            - static_checks
            - security
            - test
            - coverage
