version: 2.1

references:
  parameters: &parameters
    node_version: '12.18.3'

orbs:
  micro-app: wealthsimple/micro-app@dev:master
  sonarqube: wealthsimple/sonarqube-scanner@dev:master

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - micro-app/checkout:
          <<: *parameters
          name: checkout
      - micro-app/security:
          <<: *parameters
          name: security
          context: wealthsimple
          requires:
            - checkout
      - micro-app/test:
          <<: *parameters
          name: test
          requires:
            - checkout
      - micro-app/static_checks:
          <<: *parameters
          name: static_checks
          requires:
            - checkout
      - micro-app/semantic_release:
          <<: *parameters
          name: semantic_release
          context: wealthsimple
          filters:
            branches:
              only: master
          requires:
            - checkout
            - static_checks
            - security
            - test
      - sonarqube/scan:
          name: sonar_scan
          context: wealthsimple
          project_name: '${CIRCLE_REPONAME}'
          project_branch: '${CIRCLE_BRANCH}'
          requires:
            - checkout
            - test # generates the coverage files
      - sonarqube/check_quality_gate:
          name: quality_gate
          context: wealthsimple
          requires:
            - sonar_scan